### ISSUE TITLE
nvcuvid.h: No such file or directory

### ISSUE THREAD

**Issue by Luyang1125** [NVIDIA/NvPipe#12]
Hi,

I got the error when compiling this project on Ubuntu 16.04: **nvcuvid.h: No such file or directory**. Could you let me know how to solve this issue?

The detail logs shown on the terminal is here:

**-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda (found version "9.0") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Could NOT find EGL (missing:  EGL_LIBRARY EGL_opengl_LIBRARY EGL_INCLUDE_DIR) 
-- Could NOT find GLEW (missing:  GLEW_INCLUDE_DIR GLEW_LIBRARY) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/luyang/Documents/NvPipe-master/build
luyang@luyang-ubuntu:~/Documents/NvPipe-master/build$ make
[ 12%] Building NVCC (Device) object CMakeFiles/nvpipe.dir/convert.o
Scanning dependencies of target nvpipe
[ 25%] Building C object CMakeFiles/nvpipe.dir/debug.c.o
[ 37%] Building C object CMakeFiles/nvpipe.dir/decode.c.o
/home/luyang/Documents/NvPipe-master/decode.c:44:21: fatal error: nvcuvid.h: No such file or directory
compilation terminated.
CMakeFiles/nvpipe.dir/build.make:93: recipe for target 'CMakeFiles/nvpipe.dir/decode.c.o' failed
make[2]: *** [CMakeFiles/nvpipe.dir/decode.c.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/nvpipe.dir/all' failed
make[1]: *** [CMakeFiles/nvpipe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2**

**Comment by tfogal** [comment]
Hi Luyang,

I have heard that CUDA 9 changed the setup of the SDK, as mentioned in issue #11.  If you could confirm that the header is *not* present on your system, and furthermore that it is installed as part of a CUDA 8 SDK, that would clarify.

Of course, patches would be welcome too!

**Comment by renewagner** [comment]
I can confirm that nvcuvid.h used to be shipped in CUDA < 9.0 but is gone now. Starting with CUDA 9.0 there's a dynlink_nvcuvid.h instead which appears to be API compatible. I've created a pull request to use this depending on the CUDA version. I cannot test decoding, unfortunately, but encoding still works fine with either CUDA 8.0 or 9.1 on a Quadro K2000M and GTX 1080.

**Comment by sasmaster** [comment]
Hi! I have a related question. I have downloaded the latest video SDK. And for NVDEC there is no dynlink_nvcuvid anymore but just nvcuvid. And there is a also a static lib for Windows only. What does that mean? How do I link on Linux? Do the latest drivers for linux come with static lib for nvcuvid?

**Comment by jtk19** [comment]
I cloned this ffmpeg_libyami repo and copied the 2 cuda headers directly under /usr/include/

https://github.com/intel/ffmpeg_libyami/tree/master/compat/cuda

And then I installed all the ffmpeg -dev libraries with apt-get.

The hack worked.  The compilation found /usr/include/nvcuid.h and proceeded the compination through to the end.

**Comment by tbiedert** [comment]
Thanks @jtk19 ! Which version of NvPipe are you building?

The latest commit including Video Codec SDK 9 should contain everything you need, including the [headers ](https://github.com/NVIDIA/NvPipe/tree/master/src/Video_Codec_SDK_9.0.20/include)you mentioned. That include directory is also considered in [CMake](https://github.com/NVIDIA/NvPipe/blob/master/CMakeLists.txt#L103).
